thisdir=pwd;
addpath([thisdir, '/classifiers'],...
        [thisdir, '/helper_fcns'],...
        [thisdir, '/helper_fcns/samplers'],...
        [thisdir, '/tests'],...
        [thisdir, '/data_munging'],...
        [thisdir, '/Fig_scripts'],...
        [thisdir, '/Fig_scripts/Fig1'],...
        [thisdir, '/Fig_scripts/Fig2'],...
        [thisdir, '/Fig_scripts/generate_panels']);