lic=license;
if strcmp(lic,'359028')
    rootdir='/ytmp/Dropbox/Research/working/A/LOL/Code/';
elseif strcmp(lic,'703789')
    rootdir='~/Research/working/A/LOL/Code/';
end

addpath([rootdir, 'Classifiers'],...
        [rootdir, 'DataScripts'],...
        [rootdir, 'DataScripts/amen'],...
        [rootdir, 'DataScripts/mnist'],...
        [rootdir, 'DataScripts/pancreas'],...
        [rootdir, 'FigScripts'],...
        [rootdir, 'FigScripts/Fig1'],...
        [rootdir, 'FigScripts/Fig2'],...
        [rootdir, 'FigScripts/Fig3'],...
        [rootdir, 'HelperFcns'],...
        [rootdir, 'Tests']);    