fpath = mfilename('fullpath');
p = genpath(fpath(1:end-11));

% addpath([rootdir, 'Classifiers'],...
%         [rootdir, 'DataScripts'],...
%         [rootdir, 'DataScripts/amen'],...
%         [rootdir, 'DataScripts/mnist'],...
%         [rootdir, 'DataScripts/pancreas'],...
%         [rootdir, 'FigScripts'],...
%         [rootdir, 'FigScripts/Fig1'],...
%         [rootdir, 'FigScripts/Fig2'],...
%         [rootdir, 'FigScripts/Fig3'],...
%         [rootdir, 'HelperFcns'],...
%         [rootdir, 'Tests']);    