thisdir=pwd;
addpath([thisdir, '/../classifiers'],...
        [thisdir, '/../helper_fcns'],...
        [thisdir, '/../helper_fcns/samplers'],...
        [thisdir, '/../data_munging'],...
        [thisdir, '/../generate_figures'],...
        [thisdir, '/../generate_figures/generate_panels']);